-- Core schema. Idempotent: safe on fresh and on upgraded legacy databases.

CREATE TABLE IF NOT EXISTS author (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author     VARCHAR(255) NOT NULL,
    born_died  VARCHAR(255),
    fimage     INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS form (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form       VARCHAR(255),
    fimage     INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS location (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location   VARCHAR(255),
    fimage     INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS school (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school     VARCHAR(255),
    fimage     INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS timeframe (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timeframe  VARCHAR(255),
    fimage     INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS type (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(255),
    fimage     INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS art (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255),
    date         VARCHAR(100),
    technique    VARCHAR(500),
    url          VARCHAR(255),
    author_id    INTEGER NOT NULL,
    form_id      INTEGER NOT NULL,
    location_id  INTEGER NOT NULL,
    school_id    INTEGER NOT NULL,
    timeframe_id INTEGER NOT NULL,
    type_id      INTEGER NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS log_table (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   VARCHAR(50) NOT NULL,
    value      VARCHAR(5000) NOT NULL,
    ip         VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stored, indexed full-text vectors. Artwork vectors are stemmed (English);
-- author names use the 'simple' configuration so names are never stemmed.
ALTER TABLE art    ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(technique, ''))) STORED;
ALTER TABLE author ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('simple', coalesce(author, ''))) STORED;

CREATE INDEX IF NOT EXISTS idx_art_search        ON art    USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_author_search     ON author USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_art_author_id     ON art (author_id);
CREATE INDEX IF NOT EXISTS idx_art_form_id       ON art (form_id);
CREATE INDEX IF NOT EXISTS idx_art_location_id   ON art (location_id);
CREATE INDEX IF NOT EXISTS idx_art_school_id     ON art (school_id);
CREATE INDEX IF NOT EXISTS idx_art_timeframe_id  ON art (timeframe_id);
CREATE INDEX IF NOT EXISTS idx_art_type_id       ON art (type_id);
CREATE INDEX IF NOT EXISTS idx_author_name       ON author (author);
CREATE INDEX IF NOT EXISTS idx_log_category_time ON log_table (category, created_at);
CREATE INDEX IF NOT EXISTS idx_log_created_at    ON log_table (created_at);

-- Referential integrity. Legacy "0 = none" feature images become NULL first.
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['author', 'form', 'location', 'school', 'timeframe', 'type'] LOOP
        EXECUTE format('UPDATE %I SET fimage = NULL WHERE fimage = 0 OR fimage NOT IN (SELECT id FROM art)', t);

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_art_' || t) THEN
            EXECUTE format(
                'ALTER TABLE art ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES %I (id) ON DELETE RESTRICT',
                'fk_art_' || t, t || '_id', t
            );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_' || t || '_fimage') THEN
            EXECUTE format(
                'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (fimage) REFERENCES art (id) ON DELETE SET NULL',
                t, 'fk_' || t || '_fimage'
            );
        END IF;
    END LOOP;
END
$$;

-- Denormalised read view for ad-hoc SQL access (the API queries tables directly).
CREATE OR REPLACE VIEW artdata AS
SELECT a.id, a.title, a.date, a.technique, a.url,
       a.author_id, au.author, au.born_died,
       a.form_id, f.form,
       a.location_id, l.location,
       a.school_id, s.school,
       a.timeframe_id, t.timeframe,
       a.type_id, ty.type
FROM art a
LEFT JOIN author    au ON au.id = a.author_id
LEFT JOIN form      f  ON f.id  = a.form_id
LEFT JOIN location  l  ON l.id  = a.location_id
LEFT JOIN school    s  ON s.id  = a.school_id
LEFT JOIN timeframe t  ON t.id  = a.timeframe_id
LEFT JOIN type      ty ON ty.id = a.type_id;
