-- PostgreSQL Schema for Art Catalogue Database

-- Create sequence for auto-increment IDs
CREATE SEQUENCE art_id_seq START 1;
CREATE SEQUENCE author_id_seq START 1;
CREATE SEQUENCE form_id_seq START 1;
CREATE SEQUENCE location_id_seq START 1;
CREATE SEQUENCE school_id_seq START 1;
CREATE SEQUENCE timeframe_id_seq START 1;
CREATE SEQUENCE type_id_seq START 1;
CREATE SEQUENCE log_table_id_seq START 1;

-- ART table - Main artworks table
CREATE TABLE IF NOT EXISTS "ART" (
    "ID" INTEGER NOT NULL DEFAULT nextval('art_id_seq') PRIMARY KEY,
    "TITLE" VARCHAR(118),
    "DATE" VARCHAR(52),
    "TECHNIQUE" VARCHAR(226),
    "URL" VARCHAR(70),
    "AUTHOR_ID" INTEGER NOT NULL,
    "FORM_ID" INTEGER NOT NULL,
    "LOCATION_ID" INTEGER NOT NULL,
    "SCHOOL_ID" INTEGER NOT NULL,
    "TIMEFRAME_ID" INTEGER NOT NULL,
    "TYPE_ID" INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_art_author_id ON "ART"("AUTHOR_ID");
CREATE INDEX idx_art_form_id ON "ART"("FORM_ID");
CREATE INDEX idx_art_location_id ON "ART"("LOCATION_ID");
CREATE INDEX idx_art_school_id ON "ART"("SCHOOL_ID");
CREATE INDEX idx_art_timeframe_id ON "ART"("TIMEFRAME_ID");
CREATE INDEX idx_art_type_id ON "ART"("TYPE_ID");

-- Create tsvector index for full-text search
CREATE INDEX idx_art_title_tsvector ON "ART" USING GIN (
    to_tsvector('english', coalesce("TITLE", '') || ' ' || coalesce("TECHNIQUE", ''))
);

-- AUTHOR table
CREATE TABLE IF NOT EXISTS "AUTHOR" (
    "ID" INTEGER NOT NULL DEFAULT nextval('author_id_seq') PRIMARY KEY,
    "AUTHOR" VARCHAR(75) NOT NULL,
    "BORN_DIED" VARCHAR(75),
    "FIMAGE" INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_author_name ON "AUTHOR"("AUTHOR");

-- FORM table
CREATE TABLE IF NOT EXISTS "FORM" (
    "ID" INTEGER NOT NULL DEFAULT nextval('form_id_seq') PRIMARY KEY,
    "FORM" VARCHAR(100),
    "FIMAGE" INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_form_name ON "FORM"("FORM");

-- LOCATION table
CREATE TABLE IF NOT EXISTS "LOCATION" (
    "ID" INTEGER NOT NULL DEFAULT nextval('location_id_seq') PRIMARY KEY,
    "LOCATION" VARCHAR(100),
    "FIMAGE" INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_location_name ON "LOCATION"("LOCATION");

-- SCHOOL table
CREATE TABLE IF NOT EXISTS "SCHOOL" (
    "ID" INTEGER NOT NULL DEFAULT nextval('school_id_seq') PRIMARY KEY,
    "SCHOOL" VARCHAR(100),
    "FIMAGE" INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_school_name ON "SCHOOL"("SCHOOL");

-- TIMEFRAME table
CREATE TABLE IF NOT EXISTS "TIMEFRAME" (
    "ID" INTEGER NOT NULL DEFAULT nextval('timeframe_id_seq') PRIMARY KEY,
    "TIMEFRAME" VARCHAR(100),
    "FIMAGE" INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_timeframe_name ON "TIMEFRAME"("TIMEFRAME");

-- TYPE table
CREATE TABLE IF NOT EXISTS "TYPE" (
    "ID" INTEGER NOT NULL DEFAULT nextval('type_id_seq') PRIMARY KEY,
    "TYPE" VARCHAR(100),
    "FIMAGE" INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_type_name ON "TYPE"("TYPE");

-- LOG_TABLE table
CREATE TABLE IF NOT EXISTS "LOG_TABLE" (
    "ID" INTEGER NOT NULL DEFAULT nextval('log_table_id_seq') PRIMARY KEY,
    "CATEGORY" VARCHAR(50) NOT NULL,
    "VALUE" VARCHAR(5000) NOT NULL,
    "IP" VARCHAR(50),
    "TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_log_category ON "LOG_TABLE"("CATEGORY");
CREATE INDEX idx_log_timestamp ON "LOG_TABLE"("TIMESTAMP");

-- ARTDATA VIEW - Denormalized view for easy querying
CREATE OR REPLACE VIEW "ARTDATA" AS
SELECT
    a."ID",
    a."TITLE",
    a."DATE",
    a."TECHNIQUE",
    a."URL",
    a."AUTHOR_ID",
    a."FORM_ID",
    a."LOCATION_ID",
    a."SCHOOL_ID",
    a."TIMEFRAME_ID",
    a."TYPE_ID",
    au."AUTHOR",
    au."BORN_DIED",
    f."FORM",
    l."LOCATION",
    s."SCHOOL",
    t."TIMEFRAME",
    ty."TYPE"
FROM "ART" a
LEFT JOIN "AUTHOR" au ON a."AUTHOR_ID" = au."ID"
LEFT JOIN "FORM" f ON a."FORM_ID" = f."ID"
LEFT JOIN "LOCATION" l ON a."LOCATION_ID" = l."ID"
LEFT JOIN "SCHOOL" s ON a."SCHOOL_ID" = s."ID"
LEFT JOIN "TIMEFRAME" t ON a."TIMEFRAME_ID" = t."ID"
LEFT JOIN "TYPE" ty ON a."TYPE_ID" = ty."ID";

-- Foreign key constraints (add these after data is loaded)
ALTER TABLE "ART" ADD CONSTRAINT fk_art_author
    FOREIGN KEY ("AUTHOR_ID") REFERENCES "AUTHOR"("ID") ON DELETE CASCADE;

ALTER TABLE "ART" ADD CONSTRAINT fk_art_form
    FOREIGN KEY ("FORM_ID") REFERENCES "FORM"("ID") ON DELETE CASCADE;

ALTER TABLE "ART" ADD CONSTRAINT fk_art_location
    FOREIGN KEY ("LOCATION_ID") REFERENCES "LOCATION"("ID") ON DELETE CASCADE;

ALTER TABLE "ART" ADD CONSTRAINT fk_art_school
    FOREIGN KEY ("SCHOOL_ID") REFERENCES "SCHOOL"("ID") ON DELETE CASCADE;

ALTER TABLE "ART" ADD CONSTRAINT fk_art_timeframe
    FOREIGN KEY ("TIMEFRAME_ID") REFERENCES "TIMEFRAME"("ID") ON DELETE CASCADE;

ALTER TABLE "ART" ADD CONSTRAINT fk_art_type
    FOREIGN KEY ("TYPE_ID") REFERENCES "TYPE"("ID") ON DELETE CASCADE;
